project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - notebooks.qmd
    - assignments.qmd
    - assignment1.qmd
    - assignment2.qmd
    - assignment3.qmd
    - assignment4.qmd
    - assignment5.qmd

    
website:
  title: ""
  search: false  
  navbar:
    background: "#00205B"
    search: false
    left:
       
      - text: "Home"
        file: index.qmd

      - text: "Slide Decks"
        file: slides.qmd

      - text: "Notebooks"
        file: notebooks.qmd

      - text: "Assignments"
        file: assignments.qmd
    
format: 
  html:
    theme: cyborg
    scss: styles.css
    



